# Generated by Django 5.1.15 on 2026-09-05 02:04

from django.db import migrations, models

# The coarse muscle groups being removed, mapped to their closest granular value.
FORWARD_MUSCLE_MAP = {"legs": "quads", "arms": "biceps", "core": "abs"}
REVERSE_MUSCLE_MAP = {"quads": "legs", "biceps": "arms", "abs": "core"}


def _remap_muscles(mapping):
    def op(apps, schema_editor):
        Exercise = apps.get_model("workouts", "Exercise")
        for old, new in mapping.items():
            Exercise.objects.filter(muscle_group=old).update(muscle_group=new)

    return op


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='circuit',
            field=models.CharField(blank=True, choices=[('pull', 'Pull'), ('push', 'Push'), ('legs', 'Legs'), ('core', 'Core')], max_length=8),
        ),
        migrations.AddField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(blank=True, choices=[('barbell', 'Barbell'), ('dumbbell', 'Dumbbell'), ('cable', 'Cable'), ('machine', 'Machine'), ('plates_machine', 'Plates Machine'), ('calisthenics', 'Calisthenics')], max_length=16),
        ),
        migrations.AddField(
            model_name='exercise',
            name='secondary_muscles',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscle_group',
            field=models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('forearms', 'Forearms'), ('quads', 'Quads'), ('hamstrings', 'Hamstrings'), ('glutes', 'Glutes'), ('calves', 'Calves'), ('abs', 'Abs'), ('cardio', 'Cardio'), ('other', 'Other')], default='other', max_length=16),
        ),
        migrations.RunPython(
            _remap_muscles(FORWARD_MUSCLE_MAP),
            _remap_muscles(REVERSE_MUSCLE_MAP),
        ),
    ]
