# Generated by Django 5.1.15 on 2026-09-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_exercise_circuit_exercise_equipment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='equipment',
        ),
        migrations.AddField(
            model_name='workoutentry',
            name='equipment',
            field=models.CharField(blank=True, choices=[('barbell', 'Barbell'), ('dumbbell', 'Dumbbell'), ('cable', 'Cable'), ('machine', 'Machine'), ('plates_machine', 'Plate Loaded Machine'), ('calisthenics', 'Calisthenics')], max_length=16),
        ),
    ]
