# Generated by Django 5.1.15 on 2026-09-07 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_rename_circuit_to_split'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='split',
        ),
    ]
