# Generated by Django 5.1.15 on 2026-10-02 01:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def profile_weight_to_history(apps, schema_editor):
    """Carry each profile's single weight over as its first history entry.
    Dated today: we don't know when it was true, and as the earliest entry it
    also covers older workouts (see BodyweightLog.as_of)."""
    UserProfile = apps.get_model("workouts", "UserProfile")
    BodyweightLog = apps.get_model("workouts", "BodyweightLog")
    today = django.utils.timezone.localdate()
    BodyweightLog.objects.bulk_create(
        BodyweightLog(owner_id=p.user_id, date=today, weight_kg=p.weight_kg)
        for p in UserProfile.objects.filter(weight_kg__isnull=False)
    )


def history_to_profile_weight(apps, schema_editor):
    UserProfile = apps.get_model("workouts", "UserProfile")
    BodyweightLog = apps.get_model("workouts", "BodyweightLog")
    for p in UserProfile.objects.all():
        latest = BodyweightLog.objects.filter(owner_id=p.user_id).order_by("-date").first()
        if latest:
            p.weight_kg = latest.weight_kg
            p.save(update_fields=["weight_kg"])


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_user_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyweightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodyweights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'date'), name='unique_bodyweight_per_day')],
            },
        ),
        migrations.RunPython(profile_weight_to_history, history_to_profile_weight),
        migrations.RemoveField(
            model_name='userprofile',
            name='weight_kg',
        ),
    ]
