# Generated by Django 5.1.15 on 2026-10-02 03:12

from decimal import Decimal

from django.db import migrations, models

LB_PER_KG = Decimal("2.20462")


def snapshot_bodyweights(apps, schema_editor):
    """Give existing workouts their bodyweight snapshot, and turn existing
    calisthenics sets (whose `weight` meant added load) into stored totals.
    Mirrors BodyweightLog.as_of and WorkoutEntry.apply_bodyweight, which
    historical models can't call."""
    Workout = apps.get_model("workouts", "Workout")
    WorkoutEntry = apps.get_model("workouts", "WorkoutEntry")
    BodyweightLog = apps.get_model("workouts", "BodyweightLog")

    for workout in Workout.objects.exclude(owner=None):
        history = BodyweightLog.objects.filter(owner_id=workout.owner_id)
        entry = (
            history.filter(date__lte=workout.date).order_by("-date").first()
            or history.order_by("date").first()
        )
        workout.bodyweight_kg = entry.weight_kg if entry else None
        workout.save(update_fields=["bodyweight_kg"])

        for e in WorkoutEntry.objects.filter(workout=workout, equipment="calisthenics"):
            e.added_weight = e.weight
            if workout.bodyweight_kg is None:
                e.weight = None
            else:
                bw = workout.bodyweight_kg
                if e.weight_unit == "lb":
                    bw = (bw * LB_PER_KG).quantize(Decimal("0.1"))
                e.weight = bw + (e.added_weight or 0)
            e.save(update_fields=["weight", "added_weight"])


def unsnapshot_bodyweights(apps, schema_editor):
    WorkoutEntry = apps.get_model("workouts", "WorkoutEntry")
    for e in WorkoutEntry.objects.filter(equipment="calisthenics"):
        e.weight = e.added_weight
        e.save(update_fields=["weight"])


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_bodyweight_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='bodyweight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='workoutentry',
            name='added_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.RunPython(snapshot_bodyweights, unsnapshot_bodyweights),
    ]
