# Generated by Django 5.1.15 on 2026-10-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0010_favorite_exercises'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favoriteexercise',
            name='unique_favorite_per_profile',
        ),
        migrations.AddField(
            model_name='favoriteexercise',
            name='min_distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='favoriteexercise',
            name='min_distance_unit',
            field=models.CharField(choices=[('mi', 'mi'), ('km', 'km')], default='mi', max_length=2),
        ),
        migrations.AddConstraint(
            model_name='favoriteexercise',
            constraint=models.UniqueConstraint(fields=('profile', 'exercise', 'equipment', 'min_distance', 'min_distance_unit'), name='unique_favorite_per_profile'),
        ),
    ]
